version: "1.0"
info:
  model: int-scaffold
packages:
- name: Serengeti_GithubStg_2207Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: upperfspackage
  gitServerName: srcCtrl_bitbucket_Arti
  gitUrl: https://bitbucket.org/testartiibm
  gitUsername: artikhare
  gitBranch: master
services:
- serviceName: project.serengeti_githubstg_2207.integrations:gcd
  packages:
  - name: Serengeti_GithubStg_2207Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
